# Generated by Django 5.1 on 2024-08-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesionales.profesional')),
            ],
        ),
    ]
