# Generated by Django 4.1.1 on 2024-09-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_alter_ubicacion_profesional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacion',
            old_name='profesional',
            new_name='usuario',
        ),
    ]
